openapi: 3.0.0
info:
  title: API List Service
  description: Service to retrieve a list of APIs based on criteria
  version: 1.0.0
servers:
  - url: https://hj6cno6rh5.execute-api.ap-southeast-2.amazonaws.com/
paths:
  /apis:
    get:
      summary: Get Active APIs
      description: Retrieves a list of active APIs with an optional limit.
      parameters:
        - name: limit
          in: query
          required: false
          description: The number of APIs to return
          schema:
            type: integer
            example: 5
        - name: apistatus
          in: query
          required: false
          description: The status of the APIs to filter
          schema:
            type: string
            example: "active"
      responses:
        '200':
          description: A list of active APIs
          content:
            application/json:
              schema:
                type: object
                properties:
                  apis:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        name:
                          type: string
                        status:
                          type: string
        '400':
          description: Bad request, invalid parameters
        '500':
          description: Internal server error
    post:
      summary: Create a New API
      description: Adds a new API to the system with the given details.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                apiname:
                  type: string
                  example: "api10"
                endpoint:
                  type: string
                  example: "https://jsonplaceholder.typicode.com/posts/1"
                payload:
                  type: string
                  example: "{\"limit\": 100}"
                repo:
                  type: string
                  example: "test.com/api2"
                apistatus:
                  type: string
                  example: "active"
                method:
                  type: string
                  enum: [ "post", "get", "put", "delete" ] # Allowable HTTP methods
      responses:
        '201':
          description: API created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  message:
                    type: string
                    example: "API created successfully."
        '400':
          description: Bad request, invalid data
        '500':
          description: Internal server error
  /apis/{apiName}:
    parameters:
      - name: apiName
        in: path
        required: true
        description: The name of the API
        schema:
          type: string
    get:
      summary: Get API by Name
      description: Retrieves details of a specific API using its name.
      parameters:
        - name: apiName
          in: path
          required: true
          description: The name of the API to retrieve
          schema:
            type: string
            example: "api04"
      responses:
        '200':
          description: API details retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  apiname:
                    type: string
                  endpoint:
                    type: string
                  payload:
                    type: string
                  repo:
                    type: string
                  apistatus:
                    type: string
                  method:
                    type: string
        '404':
          description: API not found
        '500':
          description: Internal server error
    post:
      summary: Create a New API
      description: Adds a new API to the system with the given details.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                apiname:
                  type: string
                  example: "api05"
                payload:
                  type: string
                  example: "{\"limit\": 100}"
                repo:
                  type: string
                  example: "test.com/api2"
                apistatus:
                  type: string
                  example: "active"
                endpoint:
                  type: string
                  example: "https://jsonplaceholder.typicode.com/posts/1"
                lastHttpRes:
                  type: integer
                  example: 200
                method:
                  type: string
                  enum: [ "get", "post", "put", "delete" ] # Allowable HTTP methods
      responses:
        '201':
          description: API created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  message:
                    type: string
                    example: "API created successfully."
        '400':
          description: Bad request, invalid data
        '500':
          description: Internal server error
    delete:
      summary: Delete API by Name
      description: Deletes a specific API using its name.
      parameters:
        - name: apiName
          in: path
          required: true
          description: The name of the API to delete
          schema:
            type: string
            example: "api4"
      responses:
        '204':
          description: API deleted successfully
        '404':
          description: API not found
        '500':
          description: Internal server error
 
