apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  namespace: default
  name: api-master
  description: Master list of all APIs
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: openapi
  lifecycle: experimental
  owner: team-c
  definition:
    $text: https://raw.githubusercontent.com/edfajardoCiandt/bs-apis/main/openapi/api-master.yaml
